new_packages: Change library name
This commit brings the kernel version to the library name

diff --git a/user/Makefile b/user/Makefile
--- a/user/Makefile
+++ b/user/Makefile
@@ -2,16 +2,19 @@ CC=gcc
 LIBS=-ldl
 
 LIBLOAD_DIR = ../library/
-OBJECT_LIBLOAD = $(LIBLOAD_DIR)libnetdata_ebpf.so.1.0
+OBJECT_LIBLOAD = $(LIBLOAD_DIR)libnetdata_ebpf.so
 
 KERNEL_DIR = ../kernel/
 KERNEL_PROGRAM = $(KERNEL_DIR)process_kern.o
 
 #KERNEL_VERSION=$(shell basename $(realpath /usr/src/linux) | cut -f 2 -d '-' | cut -f 1,2 -d '.')
-KERNEL_VERSION="$(shell cat /usr/src/linux/include/config/kernel.release)"
+KERNEL_VERSION="$(shell if [ -f /usr/src/linux/include/config/kernel.release ]; then cat /usr/src/linux/include/config/kernel.release; else cat /proc/sys/kernel/osrelease; fi)"
 FIRST_KERNEL_VERSION=$(shell sh ../tools/complement.sh "$(KERNEL_VERSION)")
 
 NETDATA_KERNEL_VERSION=$(shell echo $(KERNEL_VERSION) | tr -s "." "_")
+
+VER_MAJOR=$(shell echo $(KERNEL_VERSION) | cut -d. -f1)
+VER_MINOR=$(shell echo $(KERNEL_VERSION) | cut -d. -f2)
 
 _LIBC ?= glibc
 
@@ -25,7 +28,7 @@ all: $(OBJECT_LIBLOAD) $(KERNEL_PROGRAM)
 	$(CC) $(EXTRA_CFLAGS) -L. -I../includes/ -o process_monitor process_user.c $(LIBS)
 	$(CC) $(EXTRA_CFLAGS) -L. -I../includes/ -o process_latency latency_process_user.c $(LIBS)
 	$(CC) $(EXTRA_CFLAGS) -pthread -L. -I../includes/ -o process_test latency_test.c $(LIBS)
-	if [ -f libnetdata_ebpf.so ]; then tar -cf ../artifacts/netdata_ebpf-$(FIRST_KERNEL_VERSION)_$(NETDATA_KERNEL_VERSION)-$(_LIBC).tar $(LIBLOAD_DIR)libbpf_kernel*.so libnetdata_ebpf.so [pr]netdata_ebpf_process.o; else echo "ERROR: Cannot find libbpf_kernel.so"; exit 1; fi
+	if [ -f libnetdata_ebpf.so.$(VER_MAJOR).$(VER_MINOR) ]; then tar -cf ../artifacts/netdata_ebpf-$(FIRST_KERNEL_VERSION)_$(NETDATA_KERNEL_VERSION)-$(_LIBC).tar $(LIBLOAD_DIR)libbpf_kernel*.so libnetdata_ebpf.so.$(VER_MAJOR).$(VER_MINOR) [pr]netdata_ebpf_process.o; else echo "ERROR: Cannot find libbpf_kernel.so"; exit 1; fi
 	if [ "$${DEBUG:-0}" -eq 1 ]; then tar -uvf ../artifacts/netdata_ebpf-$(FIRST_KERNEL_VERSION)_$(NETDATA_KERNEL_VERSION)-$(_LIBC).tar dnetdata_ebpf_process.o process_latency process_monitor process_test ../tools/check-kernel-config.sh ../tools/install.sh ../tools/uninstall.sh; fi
 	xz ../artifacts/netdata_ebpf-$(FIRST_KERNEL_VERSION)_$(NETDATA_KERNEL_VERSION)-$(_LIBC).tar
 	( cd ../artifacts; sha256sum netdata_ebpf-$(FIRST_KERNEL_VERSION)_$(NETDATA_KERNEL_VERSION)-$(_LIBC).tar.xz > netdata_ebpf-$(FIRST_KERNEL_VERSION)_$(NETDATA_KERNEL_VERSION)-$(_LIBC).tar.xz.sha256sum )
@@ -35,17 +38,17 @@ $(OBJECT_LIBLOAD):
 
 $(KERNEL_PROGRAM):
 	cd $(KERNEL_DIR) && $(MAKE) all;
-	cp $(OBJECT_LIBLOAD) libnetdata_ebpf.so
+	cp $(OBJECT_LIBLOAD)* .
 
 clean:
 	cd $(LIBLOAD_DIR) && $(MAKE) clean;
 	cd $(KERNEL_DIR) && $(MAKE) clean;
 	if [ -h /usr/lib64/libbpf_kernel.so.0 ] ; then rm /usr/lib64/libbpf_kernel.so* ; fi 
 	if [ -h /usr/lib/libbpf_kernel.so.0 ] ; then rm /usr/lib/libbpf_kernel.so* ; fi
-	if [ -f libnetdata_ebpf.so ] ; then rm libnetdata_ebpf.so; fi
+	if [ -f libnetdata_ebpf.so.$(VER_MAJOR).$(VER_MINOR) ] ; then rm libnetdata_ebpf.so.$(VER_MAJOR).$(VER_MINOR); fi
 	if [ -f libnetdata.a ] ; then rm libnetdata.a avl.o libnetdata.o ; fi
 	if [ -f pnetdata_ebpf_process.o ] ; then rm *netdata_ebpf_process.o; fi
 	rm ../artifacts/*
 
 install:
-	cp *netdata_ebpf_process.o libnetdata_ebpf.so /usr/libexec/netdata/plugins.d/
+	cp *netdata_ebpf_process.o libnetdata_ebpf.so.$(VER_MAJOR).$(VER_MINOR) /usr/libexec/netdata/plugins.d/
